#  https://www.baeldung.com/intellij-resolve-spring-boot-configuration-properties

twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Welcome to the service